### ISSUE TITLE
Increase Index Limit

### ISSUE THREAD

**Issue by pzimno** [newrelic/nri-elasticsearch#55] opened 2019-10-31 21:04 UTC
##### Description of the problem

Increase index limit to 1000 or 1500. 

We've reached a limit in the amount of indices we can send to NR through the ES integration. We currently compiled a version with the limit increased to 1000 indices and it seems to be working fine.
Not sure if this limit is because of message size limitations in the call to NR but would it be possible to get it increased? I can open up a PR if needed. 

##### OS

- [x] All of them
- [ ] Amazon Linux, all versions
- [ ] CentOS, version 6 or higher
- [ ] Debian, version 7 ("Wheezy") or higher
- [ ] Red Hat Enterprise Linux (RHEL), version 6 or higher
- [ ] Ubuntu, versions 12.04, 14.04, and 16.04 (LTS  versions)
- [ ] Windows Server, 2008 and 2012 and their service packs

**Comment by ccheek21** [comment] 2019-11-11 20:59
@pzimno Thanks for the request -- I'm checking on whether this is somethign feasible. The cap was initially introduced because of limitations of the Insights API, so I can't promise we'll be able to increase it. However, there may be other ways to work around the limitation. I'll keep you updated 👍

**Comment by otaviocarvalho** [comment] 2020-01-21 09:31
What is the expected behavior when we reach this limit? Should it drop the oldest info or panic?

I am seeing some failures related to that (error down below) using the given versions:
1. newrelic-infra-1.8.32
2. newrelic-infra-integrations-1.7.0
3. nri-elasticsearch-4.2.0

Stacktrace:
`
ERRO[0034] Integration command failed                    error="exit status 2" instance=elasticsearch integration=com.newrelic.elasticsearch prefix=config/elasticsearch stderr="[INFO] Collecting cluster metrics.\n[INFO] Collecting node metrics\n[INFO] Collecting common metrics.\n[INFO] Collecting indices metrics\n[ERR] Couldn't match index name in common index stats response: index 'staging-infra-aws_elasti_cache_memcached_cluster-v14' not contained in list

...

panic: runtime error: invalid memory address or nil pointer dereference\n[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x660d0a]\n\ngoroutine 1 [running]:\nmain.setIndicesStatsMetricsResponse(0xc4200e42c0, 0xc4203ea000, 0x518, 0x63f, 0xc4201de5a0, 0xc42017a0e0, 0x20, 0x0)\n\t/data/jenkins/infra-integrations-nri-elasticsearch-release-linux-package-3/go/src/github.com/newrelic/nri-elasticsearch/src/metrics.go:147 +0x14a\nmain.populateIndicesMetrics(0xc4200e42c0, 0x858de0, 0xc420098a40, 0xc4201de5a0, 0xc42017a0e0, 0x20, 0x0, 0x0)\n\t/data/jenkins/infra-integrations-nri-elasticsearch-release-linux-package-3/go/src/github.com/newrelic/nri-elasticsearch/src/metrics.go:107 +0x190\nmain.populateMetrics(0xc4200e42c0, 0x858de0, 0xc420098a40, 0x6bb341, 0x0)\n\t/data/jenkins/infra-integrations-nri-elasticsearch-release-linux-package-3/go/src/github.com/newrelic/nri-elasticsearch/src/metrics.go:35 +0x2b5\nmain.main()\n\t/data/jenkins/infra-integrations-nri-elasticsearch-release-linux-package-3/go/src/github.com/ne
`

After this reading this message:

`
`

**Comment by camdencheek** [comment] 2020-10-19 18:34
This should be fixed in v4.3.2

**Closed by camdencheek** 2020-10-19 18:34 UTC
